spring.config.import=optional:file:.env[.properties]

spring.application.name=avaliaFilme

# DATABASE
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# FRONTEND
frontend.url.local=${FRONTEND_URL_LOCAL}
frontend.url.prod=${FRONTEND_URL_PROD}
frontend.url.prod2=${FRONTEND_URL_PROD2}

# SWAGGER
springdoc.swagger-ui.path=/swagger.html